### ISSUE TITLE
The json for /gruposVehiculo/{id}/ultimasPosicionesVehiculos is not JSON

### ISSUE THREAD

**Issue by categulario** [codeandoxalapa/Recoleccion-Basura#3]
the first bytes of the response look like this:

`{'Page': 0, 'PageSize': 0, 'HasMoreResults': False, 'Items': ...`

and goes like this, but it does not meet the JSON specification: keys and string values should be surrounded by double quotes, true and false should be `true` and `false` (no capital letter).

It looks like the content comes that way from `us.mzoneweb.net`...

**Comment by CarlosArturoMe** [comment]
Closing this too, the answer looks right
